---
title: "Gibbs_samplar"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(tidyverse)
```

```{r}
sample_tau <- function(ys, alpha, beta, alpha0, beta0) {
  rgamma(1,
    shape = alpha0 + nrow(ys) / 2,
    rate = beta0 + 0.5 * sum((ys$y - (alpha + as.matrix(ys$x) %*% beta))^2)
  )
}

sample_alpha <- function(ys, beta, tau, mu0, tau0) {
  prec <- tau0 + tau * nrow(ys)
  mean <- (tau0 + tau * sum(ys$y - as.matrix(ys$x) %*% beta)) / prec
  rnorm(1, mean = mean, sd = 1 / sqrt(prec))
}

sample_beta <- function(ys, alpha, tau, mu0, tau0) {
  prec <- tau0 + tau * sum(ys$x * ys$x)
  mean <- (tau0 + tau * sum((ys$y - alpha) * ys$x)) / prec
  rnorm(1, mean = mean, sd = 1 / sqrt(prec))
}

```

```{r}

gibbs_sample <- function(ys,
                         tau0,
                         alpha0,
                         beta0,
                         m,
                         alpha_tau,
                         beta_tau,
                         mu_alpha,
                         tau_alpha,
                         mu_beta,
                         tau_beta) {
  tau <- numeric(m)
  alpha <- numeric(m)
  beta <- numeric(m)
  tau[1] <- tau0
  alpha[1] <- alpha0
  beta[1] <- beta0
  
  for (i in 2:m) {
    tau[i] <-
      sample_tau(ys, alpha[i - 1], beta[i - 1], alpha_tau, beta_tau)
    alpha[i] <-
      sample_alpha(ys, beta[i - 1], tau[i], mu_alpha, tau_alpha)
    beta[i] <- sample_beta(ys, alpha[i], tau[i], mu_beta, tau_beta)
  }
  
  tibble(iteration = seq_len(m),
         tau,
         alpha,
         beta)
}
```

```{r}
heights <- rnorm(100, mean = 150, sd = 20)
alpha <- 60
beta <- 0.3
sigma <- 5
weights <- purrr::map_dbl(heights, ~ rnorm(1, mean = alpha + beta * ., sd = sigma))
```

```{r}
ys <- tibble(y = weights, 
             x = heights)
```

```{r}
f = gibbs_sample(
    ys,
    tau0 = 0.5,
    alpha0 = 60,
    beta0 = 0.3,
    m = 1e4,
    alpha_tau = 3,
    beta_tau = 2,
    mu_alpha = 0,
    tau_alpha = 0.01,
    mu_beta = 0,
    tau_beta = 0.01
  )

```

```{r}
hist(f$tau)
```
```{r}
hist(f$alpha)
```
```{r}
hist(f$beta)
```


```{r}

probitll=function(beta,y,X){
  # probit likelihood
  if (is.matrix(beta)==F) beta=as.matrix(t(beta))
  n=dim(beta)[1]
  pll=rep(0,n)
  for (i in 1:n){
    lF1=pnorm(X%*%beta[i,],log=T)
    lF2=pnorm(-X%*%beta[i,],log=T)
    pll[i]=sum(y*lF1+(1-y)*lF2)
  }
  pll
}
```


Probit Metropolis–Hastings Sampler
```{r, warning=FALSE, message=FALSE}
library(lgarch)

hmflatprobit=function(niter,y,X,scale){
  p=dim(X)[2]
  mod=summary(glm(y~-1+X,family=binomial(link="probit")))
  beta=matrix(0,niter,p)
  beta[1,]=as.vector(mod$coeff[,1])
  Sigma2=as.matrix(mod$cov.unscaled)

  for (i in 2:niter){
    tildebeta=rmnorm(1,beta[i-1,],scale*Sigma2)
    llr=probitll(tildebeta,y,X)-probitll(beta[i-1,],y,X)
    if (runif(1)<=exp(llr)) beta[i,]=tildebeta
    else beta[i,]=beta[i-1,]
  }
  beta
}
```

Generate data
```{r}
set.seed(523)
n <- 100
beta_true <- matrix(c(-3, 5), ncol = 1)
x1 <- rnorm(n, 5,4)
x <- matrix(0, nrow = n, ncol = 2)
x[,1] <- rep(1, n)
x[,2] <- x1


logit_inv <- function(x){
  1/(1+exp(-x))
}


pr <- logit_inv(x %*% beta_true)
y <- rbinom(n,1,pr)
y_hat <- 2*y-1
```

```{r}
hist(y)
```

```{r}
logitll=function(beta,y,X){
  if (is.matrix(beta)==F) beta=as.matrix(t(beta))
  n=dim(beta)[1]
  pll=rep(0,n)
  for (i in 1:n){
    lF1=plogis(X%*%beta[i,],log=T)
    lF2=plogis(-X%*%beta[i,],log=T)
    pll[i]=sum(y*lF1+(1-y)*lF2)
  }
  pll
}
```

Logit Metropolis–Hastings Sampler
```{r, warning=FALSE, message=FALSE}
library(mgcv)

hmflatlogit=function(niter,y,X,scale){
  p=dim(X)[2]
  mod=summary(glm(y~-1+X,family=binomial(link="logit")))
  beta=matrix(0,niter,p)
  beta[1,]=as.vector(mod$coeff[,1])
  Sigma2=as.matrix(mod$cov.unscaled)
  for (i in 2:niter){
    tildebeta=rmvn(1,beta[i-1,],scale*Sigma2)
    llr=logitll(tildebeta,y,X)-logitll(beta[i-1,],y,X)
    if (runif(1)<=exp(llr)) beta[i,]=tildebeta
    else beta[i,]=beta[i-1,]
  }
  beta
}
```

```{r, warning=FALSE, message=FALSE}
beta_result1 <- hmflatlogit(niter = 1000,y=y,X=x, scale = 1)
```

```{r}
hist(beta_result1[,1])
```
```{r}
hist(beta_result1[,2])
```

```{r, warning=FALSE, message=FALSE}
beta_result2 <- hmflatprobit(niter = 1000,y=y,X=x, scale = 1)
```

```{r}
hist(beta_result2[,1])
```
```{r}
hist(beta_result2[,2])
```


















