---
title: "loss_function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

set up the reference distribution
```{r}
n <- 1e5
ref_dist_sample <- rnorm(n)

```

```{r}
f <- function(x){
  exp(-1/2*x^2)/sqrt(2*pi)
}
```

```{r}
x <- 1
f(x)
dnorm(x)
exp(-1/2)/sqrt(2*pi)
```
```{r}
# true value 0.282095
x <- rnorm(n)
f_list <- f(x)
(sample_mean_f <- mean(f_list))
```

```{r}
n <- 1e5
x <- rnorm(n, mean = 5, sd = 3)

(mean(log(dnorm(x, mean = 5, sd = 3))))
```

```{r}
n <- 1e5
z <- rnorm(n)

t_inv <- function(z){
  (z-5)/3
}

t_fun <- function(z){
  3*z + 5
}

(mean(log(1/3 * dnorm(z) )))

```
Check

Using posterior
```{r, warning=FALSE, message=FALSE}
set.seed(525)

library(tidyverse)

X <- 6
n <- 1e5
z <- rnorm(n)

t_fun <- function(z, phi){
  sqrt(36/13)*z + phi
}

get_Exp_post <- function(phi_in){

  mean(log( sqrt(13/36) * dnorm(z) ) -
       log(dnorm(t_fun(z, phi = phi_in),
                 mean= (4/13)*X + (9/13)*5,
                 sd = sqrt(36/13))))
}


phi_list <- seq(from = 0, to = 10, by = 0.01)

result_1 <- map_dbl(phi_list, ~get_Exp_post(.x))
```

```{r}
plot(x = phi_list, y = result_1, type = "l")
```
```{r}
phi_list[which.min(result_1)]
```
Using likelihood and prior
```{r}
likelihood_prior <- function(y){
  1/(sqrt(2*pi)*3)*exp(-1/(2*9)*(y-X)^2)*
    1/(sqrt(2*pi)*2)*exp(-1/(2*4)*(y-5)^2)
}
```

```{r}
get_Exp_likelihood_prior <- function(phi_in){

  mean(log( sqrt(13/36) * dnorm(z) ) -
       log( likelihood_prior(t_fun(z, phi = phi_in) ) )
       )
}
```

```{r}
result_2 <- map_dbl(phi_list, ~get_Exp_likelihood_prior(.x))
```

```{r}
plot(x = phi_list, y = result_2, type = "l")
```

```{r}
phi_list[which.min(result_2)]
```

true
```{r}
(4/13)*X + (9/13)*5
```

Find Grad
```{r}
get_grad <- function(phi_in){

  mean((1/9)*(t_fun(z,phi = phi_in) - X) +
         (1/4)*(t_fun(z,phi = phi_in) - 5))
}

```

```{r}
get_phi_gd <- function(phi_ini = 0,
                       step_size = 0.1,
                       max_step= 100){
  phi_list <- rep(0, 100)
  phi_list[1] <- phi_ini
  
  for(i in 2:max_step){
    phi_list[i] <- phi_list[i-1] - step_size*get_grad(phi_list[i-1])
  }
  phi_list
}
```

```{r}
phi_list <- get_phi_gd()
```
#ADAM

```{r}
plot(x = c(1:100), y = phi_list, type= "l")
```
```{r}
phi_list[100]
```

```{r}
set.seed(525)

temp <- rnorm(3)

vec1 <- matrix(c(2,1), ncol = 1)
vec2 <- matrix(c(3,2), ncol = 1)
vec3 <- matrix(c(17,7), ncol = 1)

1/3*(temp[1]*vec1 + temp[2]*vec2 + temp[3]*vec3)

cbind(vec1, vec2, vec3) %*% matrix(temp, ncol =1) * (1/3)
```

```{r, warning=FALSE, message=FALSE}
library(tidyverse)

set.seed(525)
n <- 1e3
z <- rnorm(n)
X <- 6
```

```{r}
grad_t <- function(z){
  matrix(c(z, 1), ncol = 1)
}
```

```{r}
get_first_term <- function(z){
  
  grad_t_list <- map(z, ~grad_t(.x))

  grad_t_mx <- matrix(unlist(grad_t_list), ncol = n)
  
  grad_t_mx
}
```

```{r}
grad_t_list <- map(z, ~grad_t(.x))

grad_t_mx <- matrix(unlist(grad_t_list), ncol = n)
```

```{r}
temp <- get_first_term(z)
```

```{r}
t2_fun <- function(z, phi){
  phi[1]*z + phi[2]
}
```

```{r}
get_grad_second_term <- function(z, phi_in){

  (1/9)*(t2_fun(z,phi = phi_in) - X) +
    (1/4)*(t2_fun(z,phi = phi_in) - 5)
}

```

```{r}
get_grad_second_term(z[1], phi_in = vec1)
```

```{r}
second_term <- map_dbl(z, ~get_grad_second_term(.x, phi_in = vec1))
```

```{r}
first_term <- get_first_term(z)
```

```{r}
first_term %*% second_term * 1/(length(z))
```


```{r}
get_grad_2 <- function(z, phi_input){
  first_term <- get_first_term(z)
  second_term <- map_dbl(z, ~get_grad_second_term(.x, phi_in = phi_input))
  grad <- first_term %*% second_term * 1/(length(z))
  grad[1] <- grad[1] - 1/phi_input[1]
  grad
}
```

```{r}
get_grad_2(z, vec1)
```

```{r}
phi_ini <- matrix(c(1,1), ncol = 1)

phi_temp <- phi_ini

for(i in 1:100){
  phi_new <- phi_temp - 0.1 * get_grad_2(z, phi_temp)
  phi_temp <- phi_new
}

phi_temp
```

```{r}
sqrt(36/13)
```

```{r}
get_grad_2(z, matrix(c(1.664101, 5), ncol = 1))
```

















